pipeline:
  identifier: Build_Aravinfree_jhttp_1718540989894
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: AravPracticeProject_8060387
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1718540861981
        repoName: Aravinfree/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
                  timeout: ""
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
        description: ""
